replicaCount: 2

image:
  pullPolicy: IfNotPresent

applicationName: "flair"

env:
- name: MARIADB_WRITER_USERNAME
  value: rhino_rw
- name: KEYCLOAK_SCHEME
  value: https
- name: KEYCLOAK_REALM
  value: artemis

service:
  type: ClusterIP
  port: 3000

ingress:
  paths:
    - /test

volumes: {}
volumeMounts: {}

resources:
  limits:
    memory: 256Mi
    cpu: 500m
  requests:
    memory: 128Mi
    cpu: 250m
